# Лабораторна робота №2

## Варіант №4

### Загальна постановка задач

> 1. Виконати набір вправ. Всі завдання виконати 2 способами:
>    
>    1. з використанням універсальних функцій бібліотеки NumPy;
>    
>    2. за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо);
>    
>    3. для обох випадків підрахувати час виконання скрипту та зробити висновки.
> 
> 2. Розвʼязати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
>    
>    1. матричного множення;
>    
>    2. оберненої матриці;
>    
>    3. функції `numpy.linalg.solve()`;
>    
>    Порівняти всі рішення за допомогою функції `numpy.allclose()`.
> 
> 3. Обчислити значення матричного виразу. Виконати 2 способами:
>    
>    1. з використанням універсальних функцій бібліотеки NumPy;
>    
>    2. за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо);
>    
>    3. для обох випадків підрахувати час виконання скрипту та зробити висновки.
>    
>    Порівняти всі рішення за допомогою функції `numpy.allclose()`.

*Імпортуємо модулі Numpy, random*

In [ ]:
import numpy as np
import random

### Завдання №1

#### Вправа №2

> Вводиться число $n$. Розтавити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром $n \times n$, використовуючи слайсінг.
> 
> ```python
> In [2] task_2()
>        5
> Out[2] [[0 1 0 1 0]
>         [1 0 1 0 1]
>         [0 1 0 1 0]
>         [1 0 1 0 1]
>         [0 1 0 1 0]]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_chess_matrix(n):
    matrix = np.ones((n, n), dtype=int)

    matrix[::2, ::2] = 0
    matrix[1::2, 1::2] = 0

    return matrix

In [ ]:
def numpy_print_matrix(matrix):
    print(matrix)

In [ ]:
def numpy_task_2():
    n = int(input(""))

    chess_matrix = numpy_chess_matrix(n)

#     numpy_print_matrix(chess_matrix)

In [ ]:
%time numpy_task_2()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_chess_matrix(n):
    matrix = []

    for i in range(n):
        row = []

        for j in range(n):
            if (i + j) % 2 == 0:
                row.append(0)
            else:
                row.append(1)

        matrix.append(row)

    return matrix

In [ ]:
def vanilla_print_matrix(matrix):
    for i, row in enumerate(matrix):
        if i == 0:
            print("[", end="")
        else:
            print("\n ", end="")

        print("[" + " ".join(map(str, row)) + "]", end="")

        if i == len(matrix) - 1:
            print("]")

In [ ]:
def vanilla_task_2():
    n = int(input())

    chess_matrix = vanilla_chess_matrix(n)

#     vanilla_print_matrix(chess_matrix)

In [ ]:
%time vanilla_task_2()

*Розв'язок з використанням універсальних функцій бібліотеки NumPy швидший за розв'язок за допомогою ітеративних конструкцій*

#### Вправа №4

> Вводяться числа $n$ i $m$. Вивести масив розміру $n \times m$, в якому у першому ряду (рядок з нулевим індексом) йдуть числа від 0 до $m$-1, а всі інші елементи матриці дорівнюють 0.
> 
> ```python
> In [2] task_4()
>        3 4
> Out[2] [[0 1 2 3]
>         [0 0 0 0]
>         [0 0 0 0]]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_row_matrix(n, m):
    matrix = np.zeros((n, m), dtype=int)

    matrix[0] = np.arange(m)

    return matrix

In [ ]:
def numpy_task_4():
    n, m = map(int, input().split())

    row_matrix = numpy_row_matrix(n, m)

#     numpy_print_matrix(row_matrix)

In [ ]:
%time numpy_task_4()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_row_matrix(n, m):
    matrix = []

    for i in range(n):
        if i == 0:
            row = [j for j in range(m)]
        else:
            row = [0] * m

        matrix.append(row)

    return matrix

In [ ]:
def vanilla_task_4():
    n, m = map(int, input().split())

    row_matrix = vanilla_row_matrix(n, m)

#     vanilla_print_matrix(row_matrix)

In [ ]:
%time vanilla_task_4()

*Розв'язок з використанням універсальних функцій бібліотеки NumPy швидший за розв'язок за допомогою ітеративних конструкцій*

#### Вправа №5

> Вводиться число $n$. Вивести масив розміру $n \times n$, в якому в рядках з парними індексами стоять 1, а в інших - 0.
> 
> ```python
> In [2] task_5()
>        5
> Out[2] [[1 1 1 1 1]
>         [0 0 0 0 0]
>         [1 1 1 1 1]
>         [0 0 0 0 0]
>         [1 1 1 1 1]]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_zebra_matrix(n):
    matrix = np.zeros((n, n), dtype=int)

    matrix[::2, :] = 1

    return matrix

In [ ]:
def numpy_task_5():
    n = int(input())

    zebra_matrix = numpy_zebra_matrix(n)

    numpy_print_matrix(zebra_matrix)

In [ ]:
%time numpy_task_5()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_zebra_matrix(n):
    matrix = []

    for i in range(n):
        if i % 2 == 0:
            row = [1] * n
        else:
            row = [0] * n

        matrix.append(row)

    return matrix

In [ ]:
def vanilla_task_5():
    n = int(input())

    zebra_matrix = vanilla_zebra_matrix(n)

    vanilla_print_matrix(zebra_matrix)

In [ ]:
%time vanilla_task_5()

# *Розв'язок з використанням універсальних функцій бібліотеки NumPy швидший за розв'язок за допомогою ітеративних конструкцій*

#### Вправа №8

> З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.
> 
> ```python
> In  [2] task_8()
>         3 4 0 9 8 2 4 0 8 4 0
> Out [2] Нулів: 3
>         Не нулів: 8
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_count_zeros_and_non_zeros(array):
    array = np.array(array)

    zero_count = np.sum(array == 0)
    non_zero_count = np.sum(array != 0)

    return zero_count, non_zero_count

In [ ]:
def numpy_task_8():
    array = list((map(int, input().split())))

    zero_count, non_zero_count = numpy_count_zeros_and_non_zeros(array)

    print("Нулів:", zero_count)
    print("Не нулів:", non_zero_count)

In [ ]:
%time numpy_task_8()

In [ ]:
def numpy_task_8_rand():
    n = int(input())

    array = [random.randint(0, 100) for _ in range(n)]

    zero_count, non_zero_count = numpy_count_zeros_and_non_zeros(array)

    print("Нулів:", zero_count)
    print("Не нулів:", non_zero_count)

In [ ]:
%time numpy_task_8_rand()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_count_zeros_and_non_zeros(array):
    zero_count = 0
    non_zero_count = 0

    for number in array:
        if number == 0:
            zero_count += 1
        else:
            non_zero_count += 1

    return zero_count, non_zero_count

In [ ]:
def vanilla_task_8():
    array = list((map(int, input().split())))

    zero_count, non_zero_count = vanilla_count_zeros_and_non_zeros(array)

    print("Нулів:", zero_count)
    print("Не нулів:", non_zero_count)

In [ ]:
%time vanilla_task_8()

In [ ]:
def vanilla_task_8_rand():
    n = int(input())

    array = [random.randint(0, 100) for _ in range(n)]

    zero_count, non_zero_count = vanilla_count_zeros_and_non_zeros(array)

    print("Нулів:", zero_count)
    print("Не нулів:", non_zero_count)

In [ ]:
%time vanilla_task_8_rand()

*Розв'язок за допомогою ітеративних конструкцій швидший за розв'язок з використанням універсальних функцій бібліотеки NumPy*

#### Вправа №9

> Вводиться число $n$. Створити масив значень від $n$ до 0.
> 
> ```python
> In  [2] task_9()
>         10
> Out [2] [10 9 8 7 6 5 4 3 2 1 0]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_reversed_range(n):
    reversed_range = np.arange(n, -1, -1)

    return reversed_range

In [ ]:
def numpy_print_array(array):
    print(array)

In [ ]:
def numpy_task_9():
    n = int(input())

    array = numpy_reversed_range(n)

    numpy_print_array(array)

In [ ]:
%time numpy_task_9()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_reversed_range(n):
    reversed_range = list(range(n, -1, -1))

    return reversed_range

In [ ]:
def vanilla_print_array(array):
    print("[" + " ".join(map(str, array)) + "]")

In [ ]:
def vanilla_task_9():
    n = int(input(""))

    array = vanilla_reversed_range(n)

    vanilla_print_array(array)

In [ ]:
%time vanilla_task_9()

*Розв'язок з використанням універсальних функцій бібліотеки NumPy трохи швидший за розв'язок за допомогою ітеративних конструкцій*

#### Вправа №12

> Створити масив одиниць розміром $n \times n$ та створити в ньому "рамку", що утворюється з 0.
> 
> ```python
> In  [2] task_12()
>         4
> Out [2] [[0. 0. 0. 0.]
>          [0. 1. 1. 0.]
>          [0. 1. 1. 0.]
>          [0. 0. 0. 0.]]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_frame_matrix(n):
    matrix = np.ones((n, n), dtype=float)

    matrix[0, :] = 0.
    matrix[-1, :] = 0.

    matrix[:, 0] = 0.
    matrix[:, -1] = 0.

    return matrix

In [ ]:
def numpy_task_12():
    n = int(input())

    matrix = numpy_frame_matrix(n)

    numpy_print_matrix(matrix)

In [ ]:
%time numpy_task_12()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_frame_matrix(n):
    matrix = []

    for i in range(n):
        row = []

        for j in range(n):
            if i == 0 or i == n - 1 or j == 0 or j == n - 1:
                row.append(0.0)
            else:
                row.append(1.0)

        matrix.append(row)

    return matrix

In [ ]:
def vanilla_task_12():
    n = int(input())

    matrix = vanilla_frame_matrix(n)

    vanilla_print_matrix(matrix)

In [ ]:
%time vanilla_task_12()

#### *Розв'язок з використанням універсальних функцій бібліотеки NumPy швидший за розв'язок за допомогою ітеративних конструкцій*

#### Вправа №13

> Розмістити на полі $8 \times 8$ нулі та одиниці в шаховому порядку, використовуючи функцію повторення (*).
> 
> ```python
> In  [2] task_13()
> Out [2] [[0 1 0 1 0 1 0 1]
>          [1 0 1 0 1 0 1 0]
>          [0 1 0 1 0 1 0 1]
>          [1 0 1 0 1 0 1 0]
>          [0 1 0 1 0 1 0 1]
>          [1 0 1 0 1 0 1 0]
>          [0 1 0 1 0 1 0 1]
>          [1 0 1 0 1 0 1 0]]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_8x8_chess_matrix():
    matrix = np.zeros((8, 8), dtype=int)

    matrix[::2, 1::2] = 1
    matrix[1::2, ::2] = 1

    return matrix

In [ ]:
def numpy_task_13():
    matrix = numpy_8x8_chess_matrix()

    numpy_print_matrix(matrix)

In [ ]:
%time numpy_task_13()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_8x8_chess_matrix():
    matrix = []

    for i in range(8):
        if i % 2 == 0:
            row = [0, 1] * 4 
        else:
            row = [1, 0] * 4 

        matrix.append(row)

    return matrix

In [ ]:
def vanilla_task_13():
    matrix = vanilla_8x8_chess_matrix()

    vanilla_print_matrix(matrix)

In [ ]:
%time vanilla_task_13()

*Розв'язок за допомогою ітеративних конструкцій швидший за розв'язок з використанням універсальних функцій бібліотеки NumPy*

#### Вправа №15

> Заповнити парні стовпчики матриці розміром $n \times n$ одиницями, а непарні - нулями.
> 
> ```python
> In  [2] task_15()
>         5
> Out [2] [[0 1 0 1 0]
>          [0 1 0 1 0]
>          [0 1 0 1 0]
>          [0 1 0 1 0]
>          [0 1 0 1 0]]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_striped_matrix(n):
    matrix = np.zeros((n, n), dtype=int)

    matrix[:, 1::2] = 1

    return matrix

In [ ]:
def numpy_task_15():
    n = int(input())

    matrix = numpy_striped_matrix(n)

    numpy_print_matrix(matrix)

In [ ]:
%time numpy_task_15()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_striped_matrix(n):
    matrix = []

    for i in range(n):
        row = []

        for j in range(n):
            if j % 2 == 0:
                row.append(0)
            else:
                row.append(1)

        matrix.append(row)

    return matrix

In [ ]:
def vanilla_task_15():
    n = int(input())

    matrix = vanilla_striped_matrix(n)

    vanilla_print_matrix(matrix)

In [ ]:
%time vanilla_task_15()

*Розв'язок з використанням універсальних функцій бібліотеки NumPy швидший за розв'язок за допомогою ітеративних конструкцій*

#### Вправа №19

> Згенерувати вектор із $n$ елементів, що рівномірно розміщені на інтервалі $(0, 1)$ - тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми.
> 
> ```python
> In  [2] task_20()
>         10
> Out [2] [0.091 0.182 0.273 0.364 0.455 0.545 0.636
> 0.727 0.818 0.909]
> ```

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_evenly_spaced_array(n):
    array = np.linspace(0.0, 1.0, n + 1, endpoint=False)[1:]

    array = np.around(array, decimals=3)

    return array

In [ ]:
def numpy_task_19():
    n = int(input(""))

    array = numpy_evenly_spaced_array(n)

    numpy_print_array(array)

In [ ]:
%time numpy_task_19()

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def vanilla_evenly_spaced_array(n):
    array = [round(0.0 + i * (1.0 - 0.0) / (n + 1), 3) for i in range(1, n + 1)]

    return array

In [ ]:
def vanilla_task_19():
    n = int(input())

    array = vanilla_evenly_spaced_array(n)

    vanilla_print_array(array)

In [ ]:
%time vanilla_task_19()

*Розв'язок з використанням універсальних функцій бібліотеки NumPy та розв'язок за допомогою ітеративних конструкцій однакові за швидкістю*

### Завдання №2

> Розвʼязати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
> 
> a) матричного множення;
> 
> b) оберненої матриці;
> 
> c) функції `numpy.linalg.solve()`
> 
> Порівняти всі рішення за допомогою функції `numpy.allclose()`.
> 
> $$
\left\{ 
\begin{array}{c}
x_1 + 2x_2 + 3x_3 + 4x_4 = 5 \\
2x_1 + x_2 + 2x_3 + 3x_4 = 1 \\
3x_1 + 2x_2 + x_3 + 2x_4 = 1 \\
4x_1 + 3x_2 + 2x_3 + x_4 = -5   
\end{array}
\right.
$$

*Знаходимо розвʼязок системи за допомогою формул Крамера*

In [ ]:
def cramer4x4(a, b):
    mask = np.broadcast_to(np.diag([1, 1, 1, 1]), [4, 4, 4]).swapaxes(0, 1)
    Ms = np.where(mask, np.repeat(b, 4).reshape(4, 4), a)
    return np.linalg.det(Ms) / np.linalg.det(a)

In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [2, 1, 2, 3],
    [3, 2, 1, 2],
    [4, 3, 2, 1]
])

In [ ]:
b = np.array([5, 1, 1, -5])

In [ ]:
solution = cramer4x4(a, b)

print(solution)

##### Перевірка за допомогою матричного множення:

In [ ]:
print(np.allclose(a @ solution, b))

##### Перевірка за допомогою оберненої матриці:

In [ ]:
print(np.allclose(np.linalg.inv(a) @ b, solution))

##### Перевірка за допомогою функції `numpy.linalg.solve()`:

In [ ]:
print(np.allclose(np.linalg.solve(a, b), solution))

### Завдання №3

> Обчислити значення матричного виразу. Виконати 2 способами:
> 
> а) з використанням універсальних функцій бібліотеки NumPy
> 
> b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо).
> 
> c) для обох випадків підрахувати час виконання скрипту та зробити висновок.
> 
> Порівняти всі рішення за допомогою функції `numpy.allclose()`.
> 
> $$ 2(A - B)(A^2 + B) $$
>
> $$ \mathrm{де} \; A = \begin{pmatrix} 5 & 1 & 7 \\ -10 & -2 & 1 \\ 0 & 1 & 2 \end{pmatrix}, \; B = \begin{pmatrix} 2 & 4 & 1 \\ 3 & 1 & 0 \\ 7 & 2 & 1 \end{pmatrix} $$

##### Розв'язок з використанням універсальних функцій бібліотеки NumPy:

In [ ]:
def numpy_solver():
    a = np.array([
        [5, 1, 7],
        [-10, -2, 1],
        [0, 1, 2]
    ])

    b = np.array([
        [2, 4, 1],
        [3, 1, 0],
        [7, 2, 1]
    ])

    result = 2 * (a - b) @ (a @ a + b)
    
    return result

In [ ]:
%time numpy_result = numpy_solver()

numpy_print_matrix(numpy_result)

##### Розв'язок за допомогою ітеративних конструкцій (з використанням циклів, спискових включень, тощо):

In [ ]:
def subtract_matrices(matrix_l, matrix_r):
    if len(matrix_l) != len(matrix_r) or len(matrix_l[0]) != len(matrix_r[0]):
        raise ValueError("Матриці мають різну розмірність")

    result = []
    for i in range(len(matrix_l)):
        row = []
        for j in range(len(matrix_l[0])):
            row.append(matrix_l[i][j] - matrix_r[i][j])
        result.append(row)

    return result

In [ ]:
def add_matrices(matrix_l, matrix_r):
    if len(matrix_l) != len(matrix_r) or len(matrix_l[0]) != len(matrix_r[0]):
        raise ValueError("Матриці мають різну розмірність")

    result = []
    for i in range(len(matrix_l)):
        row = []
        for j in range(len(matrix_l[0])):
            row.append(matrix_l[i][j] + matrix_r[i][j])
        result.append(row)

    return result

In [ ]:
def multiply_matrices(matrix_l, matrix_r):
    if len(matrix_l[0]) != len(matrix_r):
        raise ValueError("Неправильні розміри матриць для множення")

    result = [[0 for _ in range(len(matrix_r[0]))] for _ in range(len(matrix_l))]

    for i in range(len(matrix_l)):
        for j in range(len(matrix_r[0])):
            for k in range(len(matrix_r)):
                result[i][j] += matrix_l[i][k] * matrix_r[k][j]

    return result

In [ ]:
def multiply_matrix_by_scalar(matrix, scalar):
    result = []

    for row in matrix:
        new_row = [scalar * element for element in row]
        result.append(new_row)

    return result

In [ ]:
def vanilla_solver():
    a = [[5, 1, 7],
         [-10, -2, 1],
         [0, 1, 2]]

    b = [[2, 4, 1],
         [3, 1, 0],
         [7, 2, 1]]

    c1 = subtract_matrices(a, b)
    c2 = multiply_matrices(a, a)
    c3 = add_matrices(c2, b)
    c4 = multiply_matrices(c1, c3)
    result = multiply_matrix_by_scalar(c4, 2)
    
    return result

In [ ]:
%time vanilla_result = vanilla_solver()

vanilla_print_matrix(vanilla_result)

##### Перевірка рішень:

In [ ]:
print(np.allclose(numpy_result, vanilla_result))

*Розв'язок з використанням універсальних функцій бібліотеки NumPy та розв'язок за допомогою ітеративних конструкцій однакові за швидкістю*

### Q&A

##### 1) Яка основна мета створення NumPy?

Основною метою створення NumPy було уникнення неоднозначності при використанні перших бібліотек спеціалізованих обчислень таких як Numeric та Numarray. На даний момент бібліотека використовується як зручний інструмент для роботи з багатовимірними масивами та операціями над ними. 

##### 2) Наведіть основні ознаки, що відрізняє `ndarray` від списків Python.

NumPy `ndarray` кращий за Python `list` у наступних напрямках:

1. Розмір - структура даних NumPy займає менше місця;

2. Продуктивність - структура даних NumPy швидша;

3. Функціональність - структури даних NumPy мають оптимізовані функції, такі як вбудовані операції лінійної алгебри.

##### 3) Перерахуйте основні атрибути `ndarray`.

`ndarray` має наступні атрибути:

- `ndim` - кількість осей (вимірів)

- `shape` - розмір кожної осі

- `size` - загальний розмір масиву

- `dtype` - тип елементів масиву

- `itemsize` - розмір в байтах кожного елементу

- `nbytes` - загальний розмір масиву в байтах

##### 4) Перерахуйте способи створення масивів `ndarray`.

Існує два способи створення масивів:

1) Передача списку Python у функцію `array()`:
   
   ```python
   list = [1, 2, 3]
   
   array = np.array(list)
   ```

2) Або передача списку безпосередньо:
   
   ```python
   array = np.array([1, 2, 3])
   ```

##### 5) Наведіть основні стандартні типи даних NumPy.

Основними типами даних NumPy є:

- bool_ - Boolean (True або False), що зберігається як байт

- int_ - Цілочисельний тип за замовчуванням (такий же,
  
  як int64 або int32)

- intc - Ідентично int (як правило int32 або int64)

- intp - Ціле число, що використовується для індексації
  
  (як правило int32 або int64)

- int8 - Byte (від –128 до 127)

- int16 - Ціле (від –32768 до 32767)

- int32 - Ціле (від –2147483648 до 2147483647)

- int64 - Ціле (від –9223372036854775808 до
  
  9223372036854775807)

- uint8 - Ціле без знаку (від 0 до 255)

- uint16 - Ціле без знаку (від 0 до 65535)

- uint32 - Ціле без знаку (від 0 до 4294967295)

- uint64 - Ціле без знаку (від 0 до 18446744073709551615)

- float_ - Скорочення для float64

- float16 - Число з рухомою крапкою половинної точності,
  знаковий біт, 5-бітна експонента, 10 біт мантиси

- float32 - Число з рухомою крапкою одинарної точності,
  знаковий біт, 8-бітна експонента, 23 біти мантиси

- float64 - Число з рухомою крапкою подвійної точності,
  знаковий біт, 11-бітна експонента, 52 біти
  мантиси

- complex_ - Скорочення для complex128

- complex64 - Комплексне число, представлене двома 32-
  
  бітними числами з рухомою крапкою

- complex128 - Комплексне число, представлене двома 64-
  
  бітними числами з рухомою крапкою

##### 6) Що відбудеться при спробі призначення елементу `a[0] = 4.897` масива `ndarray`, що має `dtype=int`?

float-значення буде приведено до int

##### 7) Що відбудеться при спробі призначення елементу `a[0] = ʼhelloʼ` масива `ndarray`, що має `dtype=int`?

Виникне ValueError

##### 8) В чому відмінність функцій для зміни форми масиву `reshape()` і `resize()`?

Метод `resize()` нічого не повертає, але переформатовує масив, на відміну методу `reshape()`, що тільки повертає представлення масиву, а не сам масив.

##### 9) Наведіть відомі вам способи визначення часу виконання коду.

Існують чотири команди визначенню часу:

- `%time` – час виконання одного оператора;

- `%timeit` – середній час повторного виконання одного
  оператора для більшої точності;

- `%%time` – час виконання всього коду в комірці;

- `%%timeit` – середній час виконання всього коду в комірці.

Також можна використовувати функцію `time()` з модуля `time`, а потім знаходити різницю між двома викликами цієї функції.

##### 10) Перерахуйте арифметичні функції NumPy.

Основні арифметичні функції:

- `np.add` - Додавання (1 + 1 = 2)

- `np.subtract` - Віднімання (2 – 1 = 1)

- `np.negative` - Унарний мінус (–2)

- `np.multiply` - Множення (2 * 2 = 4)

- `np.divide` - Ділення (5 / 2 = 2.5)

- `np.floor_divide` - Цілочисельне ділення (5 / 2 = 2)

- `np.power` - Піднесення у степінь (2 ** 3 = 8)

- `np.mod` - Залишок від ділення (5 / 2 = 1)

##### 11) Наведіть способи виклику агрегатних функцій NumPy.

Основні способи виклику агрегатних функцій:

1) зі вказанням осі (axis)

2) без вказання осі (ахіs)

##### 12) В чому відмінність функцій стандартної бібліотеки Python від відповідних функцій NumPy?

Функції NumPy працюють швидше за відповідні вбудовані функції Python та мають додаткові параметри, що дозволяють виконувати розрахунки за означеними осями.
